Ecommerce/App/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from App import views

urlpatterns = [
   url(r'^home/', views.home, name='home'),
   url(r'^market/$', views.market, name='market'),
   url(r'^market/(\d+)/(\d+)/(\d+)/(\w+)/(\w+)/', views.marketparam, name='marketparam'),
   url(r'^cart/', views.cart, name='cart'),
   url(r'^mine/', views.mine, name='mine'),
   url(r'^register/', views.user_register, name='register'),
   url(r'^chkuser/', views.chk_username, name='chkuser'),
   url(r'^login/', views.user_login, name='login'),
   url(r'^loginout/', views.user_loginout, name='loginout'),
   url(r'^add_card_num/', views.add_card_num, name='add_card_num'),
   url(r'^sub_card_num/', views.sub_card_num, name='sub_card_num'),
   url(r'^allselected/', views.allselected, name='allselected'),
   url(r'^create/', views.create_order, name='create'),

   #gou wu che dan xuan
   url(r'^selectchange/', views.selectchange, name='selectchange'),
   #zeng jia gou wu che shang pin
   url(r'^addshopping/', views.addshopping, name='addshopping'),
   #jian shao shang pin shu liang
   url(r'^subshopping/', views.subshopping, name='subshopping'),
   #cart zong jia
   url(r'^sumcart/', views.sumcart, name='sumcart'),
   #验证登录
   url(r'^dologin/', views.dologin, name='dologin'),




]

Ecommerce/Ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
]

Ecommerce/templates/mine/mine.html
{% extends 'base_main.html' %}
{% load static %}

{% block extStyle %}
    {{ block.super }}
    <link rel="stylesheet" href=" {% static 'app/mine/css/mine.css' %}">
{% endblock %}

{% block content %}

    <div id="mine">
        <div class="fixed">


            {% if  is_login %}
                <a href="">{{ uname }}</a>
                <span><img src="{{ uicon }}"></span>
            {% else %}
                <span class="glyphicon glyphicon-user"></span>
                <a href="{% url 'app:login' %}">请登录</a>
            {% endif %}

            <p><span class="glyphicon glyphicon-thumbs-up"></span><span>等级</span></p>
            {% if not is_login %}
                <div id="regis"><a href="{% url 'app:register' %}">注册</a></div>
            {% endif %}
            <p><span class="glyphicon glyphicon-heart"></span>收藏</p>
        </div>

        <div class="mine">
            <p>我的订单<span><a href="">更多</a></span></p>
            <div id="nav">
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>代收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>退货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>售后</dd>
                        </dl>
                    </li>
                </ul>

            </div>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            <dd>代付款</dd>
                        </dl>
                    </li>

                    {% if is_login %}
                        <li>
                            <dl>
                                <a href="{% url 'app:loginout' %}">
                                    <dt>
                                        <span class="glyphicon glyphicon-usd"></span>
                                    </dt>
                                    <dd>tuichu</dd>
                                </a>
                            </dl>

                        </li>
                    {% endif %}


                </ul>

            </menu>
        </div>


    </div>
{% endblock %}