Ecommerce/App/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from App import views

urlpatterns = [
   url(r'^home/', views.home, name='home'),
   url(r'^market/$', views.market, name='market'),
   url(r'^market/(\d+)/(\d+)/(\d+)/(\w+)/(\w+)/', views.marketparam, name='marketparam'),
   url(r'^cart/', views.cart, name='cart'),
   url(r'^mine/', views.mine, name='mine'),
   url(r'^register/', views.user_register, name='register'),
   url(r'^chkuser/', views.chk_username, name='chkuser'),
   url(r'^login/', views.user_login, name='login'),
   url(r'^loginout/', views.user_loginout, name='loginout'),
   url(r'^add_card_num/', views.add_card_num, name='add_card_num'),
   url(r'^sub_card_num/', views.sub_card_num, name='sub_card_num'),
   url(r'^allselected/', views.allselected, name='allselected'),
   url(r'^create/', views.create_order, name='create'),

   #gou wu che dan xuan
   url(r'^selectchange/', views.selectchange, name='selectchange'),
   #zeng jia gou wu che shang pin
   url(r'^addshopping/', views.addshopping, name='addshopping'),
   #jian shao shang pin shu liang
   url(r'^subshopping/', views.subshopping, name='subshopping'),
   #cart zong jia
   url(r'^sumcart/', views.sumcart, name='sumcart'),
   #验证登录
   url(r'^dologin/', views.dologin, name='dologin'),




]

Ecommerce/Ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
]

Ecommerce/templates/cart/cart.html
{% extends 'base_main.html' %}
{% load static %}

{% block extStyle %}
    {{ block.super }}
    <link rel="stylesheet" href=" {% static 'app/cart/css/cart.css' %}">
{% endblock %}
{% block extScript %}
    <script type="text/javascript" src="{% static 'app/cart/js/cart.js' %}"></script>
{% endblock %}
{% block content %}

    <div id="cart">
        <h3>购物车</h3>
        <div class="full">
            <section class="clear">
                <ul>
                    <li>收货人:{{ name }}
                        <div><p><span><a href="#">修改&gt;</a></span></p></div>
                    </li>
                    <li>电话:{{ phone }}</li>
                    <li>收货地址:宝胜北里西区28号天丰利商城</li>
                </ul>
                <div class="bill">
                    <p>闪送超市</p>
                    <a href="#">凑单专区</a>
                    <p>满100减99</p>
                </div>

                <p class="delivery">
                    <span>收货时间:</span>
                    <span>一小时送达</span>
                    <a href="#">可送达&gt;</a>
                </p>
                <p class="delivery">
                    <span>留言:</span>
                    <input type="text" placeholder="有什么特殊需求">
                </p>

                <menu>

                    <ul>
                        {% for foo in cart %}



                            <li class="menuList" cartid=" {{ foo.id }}">
                                <div class="confirm">
                                    <span class="is_choose">
                                        {% if foo.is_select %}
                                            <span>√</span>
                                        {% else %}
                                            <span></span>
                                        {% endif %}



                                    </span>
                                </div>
                                <a href="#">
                                    <img src="  {{ foo.c_goods.productimg }} ">
                                    <p> {{ foo.c_goods.productlongname }}</p>
                                    <p> &yen;{{ foo.c_goods.price }}</p>
                                </a>
                                <section>
                                    <button class="subShopping">-</button>
                                    <span>{{ foo.c_num }}</span>
                                    <button class="addShopping">+</button>
                                </section>
                            </li>
                        {% endfor %}


                        <li class="payTheBill">

                            <div class="confirm" id="all_select">
                                <span id="all_select_inner" select="allselect" all_select_inner="on">
{#                                    {% ifequal allselect '1' %}#}
{#                                        <span></span>#}
{#                                    {% else %}#}
{#                                        <span>√</span>#}
{#                                    {% endifequal %}#}
                                    <span id="zhuang" >√</span>

                                </span>
                            </div>

                            <p>
                                <span>全选</span>
                                <span >总价:<span id="cartsum" >&yen;{{ cartsum }}</span></span>
                            </p>
                            {% ifequal is_select '0' %}
                                <a href="#"><span>下单</span></a>
                            {% else %}
                                <a href="{% url 'app:create' %}"><span>下单</span></a>
                            {% endifequal %}


                        </li>

                    </ul>

                </menu>

            </section>
        </div>
    </div>
{% endblock %}