Ecommerce/App/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from App import views

urlpatterns = [
   url(r'^home/', views.home, name='home'),
   url(r'^market/$', views.market, name='market'),
   url(r'^market/(\d+)/(\d+)/(\d+)/(\w+)/(\w+)/', views.marketparam, name='marketparam'),
   url(r'^cart/', views.cart, name='cart'),
   url(r'^mine/', views.mine, name='mine'),
   url(r'^register/', views.user_register, name='register'),
   url(r'^chkuser/', views.chk_username, name='chkuser'),
   url(r'^login/', views.user_login, name='login'),
   url(r'^loginout/', views.user_loginout, name='loginout'),
   url(r'^add_card_num/', views.add_card_num, name='add_card_num'),
   url(r'^sub_card_num/', views.sub_card_num, name='sub_card_num'),
   url(r'^allselected/', views.allselected, name='allselected'),
   url(r'^create/', views.create_order, name='create'),

   #gou wu che dan xuan
   url(r'^selectchange/', views.selectchange, name='selectchange'),
   #zeng jia gou wu che shang pin
   url(r'^addshopping/', views.addshopping, name='addshopping'),
   #jian shao shang pin shu liang
   url(r'^subshopping/', views.subshopping, name='subshopping'),
   #cart zong jia
   url(r'^sumcart/', views.sumcart, name='sumcart'),
   #验证登录
   url(r'^dologin/', views.dologin, name='dologin'),




]

Ecommerce/Ecommerce/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('App.urls', namespace='app')),
]

Ecommerce/templates/base.html
{#jia zai jing tai zi yuan #}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{# ding yi biao ti bian liang #}
    <title>{{ title }}</title>
{#daoru css#}
    <link rel="stylesheet" href=" {% static 'css/bootstrap.css' %}  ">
    <link rel="stylesheet" href=" {% static 'css/swiper.css' %}  ">
    <link rel="stylesheet" href=" {% static 'css/reset.css' %}  ">


{#wa keng #}
    {% block extStyle %}


    {% endblock %}
</head>
<body>
{#dao ru js  zhuyi j#}
<script type="text/javascript" src="{% static 'js/jquery.js' %}">    </script>
<script type="text/javascript" src="{% static 'js/base.js' %}">    </script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}">    </script>

<script type="text/javascript" src="{% static 'js/swiper.jquery.js' %}">    </script>

{#wa keng #}
    {% block extScript %}


    {% endblock %}

{# zhu ti #}
    {% block header %}


    {% endblock %}
    {% block content %}


    {% endblock %}
    {% block footer %}


    {% endblock %}




</body>
</html>

Ecommerce/templates/base_main.html
{% extends 'base.html' %}
{% load static %}

{% block extStyle %}
    <link rel="stylesheet" href="  {% static 'css/base.css' %} ">
{% endblock %}

{% block header %}
    <header>
        <h1>Jingdong supermarket</h1>
    </header>

{% endblock %}

{% block footer %}
    <footer>

        <a href="{% url 'app:home' %}" class="home">
            <dl>
                <dt><span>  </span></dt>
                <dd> zhuye</dd>
            </dl>
        </a>

        <a href="{% url 'app:market' %}" class="market">
            <dl>
                <dt><span>  </span></dt>
                <dd> shansong</dd>
            </dl>
        </a>

        <a href="{% url 'app:cart' %}" class="cart">
            <dl>
                <dt><span>  </span></dt>
                <dd> cart</dd>
            </dl>
        </a>

        <a href="{% url 'app:mine' %}" class="mine">
            <dl>
                <dt><span>  </span></dt>
                <dd> mine</dd>
            </dl>
        </a>



    </footer>

{% endblock %}